### ISSUE TITLE
different tags for <abe> and <term>?

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-chv#10]
It looks like `<abe>` has been changed to `+сӑр<post>` and `<term>` has been changed to `<ter>`.  I'm curious when these changes were made and what the reasoning for the changes was.

**Comment by ftyers** [comment]
* `<abe>`: `+sız<post>` in other Turkic transducers.
* `<term>` → `<ter>` ... in Giellatekno transducers.

**Comment by ftyers** [comment]
@jonorthwash should this be closed?

**Comment by jonorthwash** [comment]
Yep, questions answered, tests updated.

**Comment by jonorthwash** [comment]
I'm wondering why we don't want `+шӑн<post>` though...?
