### ISSUE TITLE
<n><pl>+сӑр<post> seems to sometimes fail

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-chv#12]
E.g.,
```
[FAIL] тетрадь<n><pl>+сӑр<post> => missing results: тетрадьсемсӗр
[FAIL] тетрадь<n><pl>+сӑр<post> => unexpected results: тетрадьсесӗр
```
```
[FAIL] июнь<n><pl>+сӑр<post> => missing results: июньсемсӗр
[FAIL] июнь<n><pl>+сӑр<post> => unexpected results: июньсесӗр
```
```
[FAIL] кукӑль<n><pl>+сӑр<post> => missing results: кукӑльсемсӗр
[FAIL] кукӑль<n><pl>+сӑр<post> => unexpected results: кукӑльсесӗр
```
```
[FAIL] тӗн<n><pl>+сӑр<post> => missing results: тӗнсемсӗр
[FAIL] тӗн<n><pl>+сӑр<post> => unexpected results: тӗнсесӗр
```
```
[FAIL] ял<n><pl>+сӑр<post> => missing results: ялсемсӗр
[FAIL] ял<n><pl>+сӑр<post> => unexpected results: ялсесӗр
```
```
[FAIL] ача<n><pl>+сӑр<post> => missing results: ачасемсӗр
[FAIL] ача<n><pl>+сӑр<post> => unexpected results: ачасесӗр
```
```
[FAIL] ҫыру<n><pl>+сӑр<post> => missing results: ҫырусемсӗр
[FAIL] ҫыру<n><pl>+сӑр<post> => unexpected results: ҫырусесӗр
```
All missing м.

**Comment by ftyers** [comment]
Fixed in ced036a

```
$ echo "ача<n><pl>+сӑр<post>" | hfst-lookup chv.autogen.hfst 
ача<n><pl>+сӑр<post>	ачасемсӗр	1,000000
```

Although is that a valid form, morphotactically? Are there any corpus examples?

**Comment by hectoralos** [comment]
These are the first ача not in sg.nom in Тантӑш:
* Чӑваш ачисен хаҫачӗ
* АЧАСЕН ТУСӗ
* Пуш уйӑхӗн 24-мӗшӗнче Шупашкарти ачасемпе ҫамрӑксен пултарулӑх
* керменӗнче ачасен канӑвне йӗркелекенсен республикӑри 1-мӗш форумӗ
* иртрӗ. Унта кану лагерӗн эмблемине [логотипне] ӳкерсе дипломсене палӑрнӑ ачасене чысларӗҫ. 138 ӗҫрен 11-ӗшӗ чи лайӑххисен йышне кӗнӗ.
* ачасен канӑвӗ» эмблема ӳкерекенсен
* пӗлтереҫҫӗ. Ачасене наци тумӗпе
* ҫут ҫанталӑка юратсан ачасем вӑйлӑ
* «DRIVE DANCE» фестивале хутшӑннӑ. Ачасем тӗрлӗ номинацире
* ҫӗнтернӗ тата призерсен йышне кӗнӗ. Йӗркелӳҫӗсем ташӑ ушкӑнӗсене кубокпа чысланӑ, кашни ачана медальпе тата ҫӗнтерӳҫӗ
* воспитатель ачасене лайӑх
* Хӗр ачасем ҫӗр­шывӑн
* пушмаклӑ конькиллӗ ачасем тухрӗҫ
* шкула ҫӳреҫҫӗ. Ара, ҫитес вӗренӳ ҫулӗнче шӑпӑрлансем парта хушшине ларӗҫ. Ачасем чӑнласах та пултаруллӑ. Софья сӑвӑсем хӑвӑрт

**Comment by jonorthwash** [comment]
@hectoralos, The question isn't about forms of ача, but about whether `<n><pl>+сӑр<post>` (of _any_ noun) is known to be used at all in Chuvash.  I.e., is it a hypothetical construction or an attested construction?

**Comment by hectoralos** [comment]
Sorry, I didn't understand because I can't see the problem. Yes, it is an absolutely normal construction. I found 60 examples in a little working corpus.

**Comment by ftyers** [comment]
@hectoralos can you paste some of them them here?

**Comment by hectoralos** [comment]
* Литература музейӗнче лекцисемсӗр тата экскурсисемсӗр пуҫне пӗрмаях тӗрлӗ ӑсталӑх класӗ, вӑйӑ уроксем иртеҫҫӗ.
* Уҫӑ уроксемсӗр пуҫне Раҫ­ҫей МЧСӗн ӗҫченӗсем эвакуацисем те ирттерӗҫ.
* Шкулти уроксемсӗр пуҫне вӗренӳ программине республикӑри театрсенчи чӑвашла спектакльсене, музейсене ҫӳрессине кӗртсен аванччӗ.
* 9 класс хыҫҫӑн тӗп предметсемсӗр пуҫне тепӗр икӗ экзамен суйлама ыйтсан тӳрех акӑлчан чӗлхине тата обществознание палӑртнӑ. Хӗр хӑйне шанать.
* Вӗренӳ расписанине тӗп предметсемсӗр пуҫне автоӗҫ, право, робототехника, кӗрешӳ ӑслайӗсем, ҫулӑм хатӗрленӗвӗ, ишесси, вулав сехечӗ кӗнӗ.
* Вӑтӑрмӗш ҫулсенче поэт сӑвӑсемсӗр пуҫне М.Горькин «Фома Гордеев» романне, А.Пушкинӑн «Борис Годунов» трагедине чӑвашла куҫарса пичетленӗ, чи ӑста тӑлмачсенчен пӗри шутланнӑ.
* Унта ачасемпе вӗрентекенсемсӗр пуҫне ашшӗ-амӑшӗ те пуҫтарӑннӑ.

**Comment by ftyers** [comment]
@hectoralos is this fixed now ?

**Comment by jonorthwash** [comment]
I was the one who originally posted it, and it looks like the relevant tests indeed pass now.
