### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-chv#20]
Verbs like кай or выля and affixes like Ай give a lot of work not because they are "irregular" but because of the stupid alien Stalinist orthography of Chuvash, that uses я, ю et al. Maybe it would be easier to have in the lexc forms like выльа, and to work in twol with pre-1936 orthography, i.e. producing e.g. кайатӑп. A final step could change all йа and ьа to я. Wouldn't it be easier?

**Comment by ftyers** [comment]
I think we have essentially that situation:

```
меню:мен%{й%}ю                       N-RADIO ;    ! "меню"         ! меню́
хӑю:хӑ%{й%}ю                         N-TU ;       ! ""
няня:нян%{й%}я                       N ;          ! ""               !АЛЕРТ(я)
аллея:алле%{й%}я                     N ;          ! "" ! алле́я
стихия:стихи%{й%}я                   N ;          ! "" ! стихи́я
```

We keep the orthography in the lemma, but add a placeholder for the й/ь in the morphotactic representation. This should do the right thing with -я and -ю. 

For -й ending, I think things already "just work":

```
$ echo "сарай<n><gen>" | hfst-lookup .deps/chv.LR.hfst 
сарай<n><gen>	сарайӑн	0,000000

$ echo "сарай<n><dat>" | hfst-lookup .deps/chv.LR.hfst 
сарай<n><dat>	сарая	0,000000
```

**Comment by hectoralos** [comment]
I was thinking mainly about verbs. You can run 
```
aq-morftest v_кай_del.yaml
aq-morftest v_выля_del.yaml
```
Мaybe for `выля` the solution can be adding `%{й%}`.

**Comment by ftyers** [comment]
I don't use the `apertium-quality` stuff. Also, I haven't really dealt with verbs yet, so it's probably just issues with the rules rather than the morphotactic representation. :)
