### ISSUE TITLE
-(л)лĂ

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-chv#6]
I've been surprised to find this suffix as a postposition. I always considered it as a form of adjectivation. Of course, it can be considered as a postposition if this is more pan-Turkic :)

In any case, the suffix has two л after a vowel. So it is similar to (ч)чен, but easier, since there are no differences between consonants.

Examples:

пуртӑллӑ from пуртӑ.
мозаикăллă from мозаика.
няньăллă from няня.
илемлӗ from илем.
хутлӑ from хут.

**Comment by hectoralos** [comment]
More cases:
аллейăллă from аллея
министерствăллă from министерство
училищӗллӗ from училище
шӑшиллӗ from шӑши
информациллӗ from информаци

**Comment by ftyers** [comment]
These now work:

```
илем<n>+ллӑ<post>	илем>{л}л{Ă}	илемлӗ
хут<n>+ллӑ<post>	хут>{л}л{Ă}	хутлӑ
министерство<n>+ллӑ<post>	министерств{о}>{л}л{Ă}	министерствӑллӑ
училище<n>+ллӑ<post>	училищ{е}>{л}л{Ă}	училищӗллӗ
мозаика<n>+ллӑ<post>	мозаик{а}>{л}л{Ă}	мозаикӑллӑ
шӑши<n>+ллӑ<post>	шӑши{й}>{л}л{Ă}	шӑшиллӗ
информаци<n>+ллӑ<post>	информаци{й}>{л}л{Ă}	информациллӗ
пуртӑ<n>+ллӑ<post>	пурт{ː}ӑ>{л}л{Ă}	пуртӑллӑ
аллея<n>+ллӑ<post>	алле{й}я>{л}л{Ă}	аллейӑллӑ
няня<n>+ллӑ<post>	нян{й}я>{л}л{Ă}	няньӑллӑ
```

In 6d2f491 .
