### ISSUE TITLE
Allative for литература-like words

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-chv#7]
Sovietisms with this unstressed ending vowels should have allatives like in similar Chuvash words ending in ӑ or ӗ. So:

```
литература<n><all> = литературалла instead of литературӑналла (cf, пуллалла from пулӑ)
няня<n><all> = нянялла instead of няньӑналла
аллея<n><all> = аллеялла instead of аллейӑналла
министерство<n><all> = министерствалла instead of министерствӑналла
училище<n><all> = училищелле instead of училищӗнелле
```

**Comment by ftyers** [comment]
@hectoralos does this also go for the dative ? Also, could you give the morphotactic form ? e.g.

```
$ echo "литература<n><all>" | hfst-lookup .deps/chv.LR.lexc.hfst 
литература<n><all>	литератур{а}>{N}{A}>лл{A}	0,000000
````

I formed the allative as you suggested based on the dative. But could it be the case that for some nouns it is not formed on the dative?

**Comment by hectoralos** [comment]
No, not for dative. It is strange, but the dative of литература is not the same as e.g. турӑ. But the allative is the same, as confirms Vinogradov's orthographic dictionary.

**Comment by ftyers** [comment]
I don't really understand, could you give me forms of the dative and the allative for all those words you give in https://github.com/apertium/apertium-chv/issues/7#issue-489668738 ?

And also for the words in https://github.com/apertium/apertium-chv/issues/3#issue-489337609 ?

**Comment by hectoralos** [comment]
Sorry, everything is correct and was wrong. I've been this evening with Anna Semënovna and Artëm Fedorynqyk to clarify this and other things, and they said that литературӑналла, etc., based on dative, are the right forms.
