### ISSUE TITLE
килчӗ/килчӗҫ

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-chv#8]
"кил" v iv past p3 sg is килчӗ instead of килтӗ
"кил" v iv past p3 pl is килчӗҫ instead of килтӗҫ
See http://wiki.apertium.org/wiki/%D0%9A%D0%B8%D0%BB

( %{T%} changes to т for the other persons in such a verb with final л, but to ч in p3.sg and p3.pl)

**Comment by ftyers** [comment]
Morphotactic form:

```
$ echo "кил<v><iv><past><p3><sg>" | hfst-lookup .deps/chv.LR.lexc.hfst 
кил<v><iv><past><p3><sg>	кил>{T}>ӗ	0,000000
```

Now:

```
$ echo "кил<v><iv><past><p3><sg>" | hfst-lookup .deps/chv.LR.hfst 
кил<v><iv><past><p3><sg>	килчӗ	0,000000
```

Check commit 9aa42d3
